### ISSUE TITLE
installation on macOS

### ISSUE THREAD

**Issue by dougwyu** [kdmurray91/axe#11]
I get this installation error on macOS 10.13.5 (using Apple's native compilers)

Scanning dependencies of target doc_onehtml
WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the imgmath_latex setting
WARNING: html_static_path entry '/Users/Negorashi2011/src/axe/docs/.static' does not exist
[  0%] Built target doc_onehtml
Scanning dependencies of target doc_man
WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.

[  0%] Built target doc_man
Scanning dependencies of target doc_html
WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the imgmath_latex setting
WARNING: html_static_path entry '/Users/Negorashi2011/src/axe/docs/.static' does not exist
[  0%] Built target doc_html
Scanning dependencies of target doc
[  0%] Built target doc
Scanning dependencies of target setup_tests
[  0%] Built target setup_tests
Scanning dependencies of target qes_static
**[  4%] Building C object src/libqes/src/CMakeFiles/qes_static.dir/qes_compat.c.o
clang: error: no such file or directory: 'NOTFOUND'**
make[2]: *** [src/libqes/src/CMakeFiles/qes_static.dir/qes_compat.c.o] Error 1
make[1]: *** [src/libqes/src/CMakeFiles/qes_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by kdmurray91** [comment]
Hmm, odd. I don't have a mac handy to try building, but could you please try running the following:

```bash
sed -e 's/${AXE_VERSION}/0.2.0/g' src/axe_config.h.in > src/axe_config.h
clang -o axe src/datrie/*.c src/gsl/*.c src/libqes/src/*.c src/*.c -Wall -std=c11 -I src -I src/datrie -I src/gsl -I src/libqes/src -lz
```
This will manually compile axe, and hopefully give a more informative error message.

**Comment by dougwyu** [comment]
I gave it a try.  no joy.  


cd ~/src
git clone --recursive https://github.com/kdmurray91/axe.git <https://github.com/kdmurray91/axe.git> axe
cd axe
sed -e 's/${AXE_VERSION}/0.2.0/g' src/axe_config.h.in > src/axe_config.h
clang -o axe src/datrie/*.c src/gsl/*.c src/libqes/src/*.c src/*.c -Wall -std=c11 -I src -I src/datrie -I src/gsl -I src/libqes/src -
lz

In file included from src/libqes/src/qes_compat.c:29:
src/libqes/src/qes_compat.h:29:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
In file included from src/libqes/src/qes_file.c:29:
In file included from src/libqes/src/qes_file.h:32:
src/libqes/src/qes_util.h:43:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
In file included from src/libqes/src/qes_libgnu.c:28:
src/libqes/src/qes_libgnu.h:31:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
In file included from src/libqes/src/qes_log.c:29:
In file included from src/libqes/src/qes_log.h:34:
src/libqes/src/qes_util.h:43:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
In file included from src/libqes/src/qes_match.c:30:
In file included from src/libqes/src/qes_match.h:33:
src/libqes/src/qes_util.h:43:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
In file included from src/libqes/src/qes_seq.c:29:
In file included from src/libqes/src/qes_seq.h:33:
src/libqes/src/qes_util.h:43:10: fatal error: 'qes_config.h' file not found
#include "qes_config.h"
         ^~~~~~~~~~~~~~

and so on

**Comment by kdmurray91** [comment]
Ah, sorry, I forgot an additional line to generate qes_config.h

```bash
sed -e 's/${AXE_VERSION}/0.3.3/g' src/axe_config.h.in > src/axe_config.h
sed -e 's/${QES_VERSION}/AXE/g' -e 's/^#cmakedefine/#define/' src/libqes/src/qes_config.h.in > src/libqes/src/qes_config.h
clang -o axe src/datrie/*.c src/gsl/*.c src/libqes/src/*.c src/*.c -Wall -std=gnu11 -I src -I src/datrie -I src/gsl -I src/libqes/src -lz
```

**Comment by kdmurray91** [comment]
Additionally, could you please post the files `build/axe_config.h` and `build/qes_config.h` which Cmake generated.

**Comment by dougwyu** [comment]
okay, that worked!  thanks

doug

**Comment by dougwyu** [comment]
`/*
 * ============================================================================
 *
 *       Filename:  axe_config.h.in
 *    Description:  Pull in build system definitions
 *      Copyright:  2014-2016 Kevin Murray <kdmfoss@gmail.com>
 *        License:  GNU GPL v3+
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ============================================================================
 */

#ifndef AXE_CONFIG_H
#define AXE_CONFIG_H

#define _GNU_SOURCE

#define AXE_VERSION "0.3.3-2-ge23af27"

#endif /* AXE_CONFIG_H */
`

**Comment by dougwyu** [comment]
`/*
 * Copyright 2015 Kevin Murray <spam@kdmurray.id.au>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * ============================================================================
 *
 *       Filename:  qes_config.h.in
 *
 *    Description:  Define various things from CMake.
 *
 *        Created:  15/08/14 12:09:59
 *        License:  GPLv3+
 *       Compiler:  gcc, clang
 *
 *         Author:  Kevin Murray, spam@kdmurray.id.au
 *
 * ============================================================================
 */

#ifndef QES_CONFIG_H
#define QES_CONFIG_H

#define LIBQES_VERSION "0.3.3-2-ge23af27"
#define GETLINE_FOUND
#define STRNDUP_FOUND
#define ZLIB_FOUND
#define GZBUFFER_FOUND
/* #undef OPENMP_FOUND */
#define ASPRINTF_FOUND
#define VASPRINTF_FOUND

/* Definitions to make changing fp type easy */
#ifdef ZLIB_FOUND
#   include <zlib.h>
#   define QES_ZTYPE gzFile
#   define QES_ZOPEN gzopen
#   define QES_ZDOPEN gzdopen
#   define QES_ZCLOSE gzclose
#   define QES_ZREAD gzread
#   define QES_ZWRITE gzwrite
#   define QES_ZFLUSH(fp) gzflush(fp, Z_SYNC_FLUSH)
#   define QES_ZFPRINTF gzprintf
#   define QES_ZFPUTS gzputs
#   define QES_ZFPUTC gzputc
#   define QES_ZFGETS gzgets
#   define QES_ZFGETC gzgetc
#   define QES_ZFUNGETC gzungetc
#   define QES_ZERR gzerror
#   define QES_ZEOF gzeof
#ifdef GZBUFFER_FOUND
#   define QES_ZBUFFER gzbuffer
#endif
#   define QES_ZSEEK gzseek
#   define QES_ZTELL gztell
#   define QES_ZREWIND gzrewind
#else
#   define QES_ZTYPE FILE*
#   define QES_ZOPEN fopen
#   define QES_ZCLOSE fclose
#   define QES_ZDOPEN fdopen
#   define QES_ZCLOSE fclose
#   define QES_ZREAD(fp, buf, ln) fread(buf, 1, ln, fp)
#   define QES_ZWRITE(fp, buf, ln) fwrite(buf, 1, ln, fp)
#   define QES_ZFLUSH fflush
#   define QES_ZFPRINTF fprintf
#   define QES_ZFPUTS(fp, s) fputs(s, fp)
#   define QES_ZFPUTC(fp, c) fputc(c, fp)
#   define QES_ZFGETS(fp, s, l) fgets(s, l, fp)
#   define QES_ZFGETC fgetc
#   define QES_ZFUNGETC fungetc
#   define QES_ZERR ferror
#   define QES_ZEOF feof
#   define QES_ZBUFFER(fp, sz) setvbuf(fp, NULL, _IOFBF, sz)
#   define QES_ZSEEK fseek
#   define QES_ZTELL ftell
#   define QES_ZREWIND rewind
#endif

#endif /* QES_CONFIG_H */
`

**Comment by dougwyu** [comment]
/*
 * Copyright 2015 Kevin Murray <spam@kdmurray.id.au>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * ============================================================================
 *
 *       Filename:  qes_config.h.in
 *
 *    Description:  Define various things from CMake.
 *
 *        Created:  15/08/14 12:09:59
 *        License:  GPLv3+
 *       Compiler:  gcc, clang
 *
 *         Author:  Kevin Murray, spam@kdmurray.id.au
 *
 * ============================================================================
 */

#ifndef QES_CONFIG_H
#define QES_CONFIG_H

#define LIBQES_VERSION "0.3.3-2-ge23af27"
#define GETLINE_FOUND
#define STRNDUP_FOUND
#define ZLIB_FOUND
#define GZBUFFER_FOUND
/* #undef OPENMP_FOUND */
#define ASPRINTF_FOUND
#define VASPRINTF_FOUND

/* Definitions to make changing fp type easy */
#ifdef ZLIB_FOUND
#   include <zlib.h>
#   define QES_ZTYPE gzFile
#   define QES_ZOPEN gzopen
#   define QES_ZDOPEN gzdopen
#   define QES_ZCLOSE gzclose
#   define QES_ZREAD gzread
#   define QES_ZWRITE gzwrite
#   define QES_ZFLUSH(fp) gzflush(fp, Z_SYNC_FLUSH)
#   define QES_ZFPRINTF gzprintf
#   define QES_ZFPUTS gzputs
#   define QES_ZFPUTC gzputc
#   define QES_ZFGETS gzgets
#   define QES_ZFGETC gzgetc
#   define QES_ZFUNGETC gzungetc
#   define QES_ZERR gzerror
#   define QES_ZEOF gzeof
#ifdef GZBUFFER_FOUND
#   define QES_ZBUFFER gzbuffer
#endif
#   define QES_ZSEEK gzseek
#   define QES_ZTELL gztell
#   define QES_ZREWIND gzrewind
#else
#   define QES_ZTYPE FILE*
#   define QES_ZOPEN fopen
#   define QES_ZCLOSE fclose
#   define QES_ZDOPEN fdopen
#   define QES_ZCLOSE fclose
#   define QES_ZREAD(fp, buf, ln) fread(buf, 1, ln, fp)
#   define QES_ZWRITE(fp, buf, ln) fwrite(buf, 1, ln, fp)
#   define QES_ZFLUSH fflush
#   define QES_ZFPRINTF fprintf
#   define QES_ZFPUTS(fp, s) fputs(s, fp)
#   define QES_ZFPUTC(fp, c) fputc(c, fp)
#   define QES_ZFGETS(fp, s, l) fgets(s, l, fp)
#   define QES_ZFGETC fgetc
#   define QES_ZFUNGETC fungetc
#   define QES_ZERR ferror
#   define QES_ZEOF feof
#   define QES_ZBUFFER(fp, sz) setvbuf(fp, NULL, _IOFBF, sz)
#   define QES_ZSEEK fseek
#   define QES_ZTELL ftell
#   define QES_ZREWIND rewind
#endif

#endif /* QES_CONFIG_H */

**Comment by dougwyu** [comment]
`#ifndef QES_CONFIG_H
#define QES_CONFIG_H

#define LIBQES_VERSION "0.3.3-2-ge23af27"
#define GETLINE_FOUND
#define STRNDUP_FOUND
#define ZLIB_FOUND
#define GZBUFFER_FOUND
/* #undef OPENMP_FOUND */
#define ASPRINTF_FOUND
#define VASPRINTF_FOUND

/* Definitions to make changing fp type easy */
#ifdef ZLIB_FOUND
#   include <zlib.h>
#   define QES_ZTYPE gzFile
#   define QES_ZOPEN gzopen
#   define QES_ZDOPEN gzdopen
#   define QES_ZCLOSE gzclose
#   define QES_ZREAD gzread
#   define QES_ZWRITE gzwrite
#   define QES_ZFLUSH(fp) gzflush(fp, Z_SYNC_FLUSH)
#   define QES_ZFPRINTF gzprintf
#   define QES_ZFPUTS gzputs
#   define QES_ZFPUTC gzputc
#   define QES_ZFGETS gzgets
#   define QES_ZFGETC gzgetc
#   define QES_ZFUNGETC gzungetc
#   define QES_ZERR gzerror
#   define QES_ZEOF gzeof
#ifdef GZBUFFER_FOUND
#   define QES_ZBUFFER gzbuffer
#endif
#   define QES_ZSEEK gzseek
#   define QES_ZTELL gztell
#   define QES_ZREWIND gzrewind
#else
#   define QES_ZTYPE FILE*
#   define QES_ZOPEN fopen
#   define QES_ZCLOSE fclose
#   define QES_ZDOPEN fdopen
#   define QES_ZCLOSE fclose
#   define QES_ZREAD(fp, buf, ln) fread(buf, 1, ln, fp)
#   define QES_ZWRITE(fp, buf, ln) fwrite(buf, 1, ln, fp)
#   define QES_ZFLUSH fflush
#   define QES_ZFPRINTF fprintf
#   define QES_ZFPUTS(fp, s) fputs(s, fp)
#   define QES_ZFPUTC(fp, c) fputc(c, fp)
#   define QES_ZFGETS(fp, s, l) fgets(s, l, fp)
#   define QES_ZFGETC fgetc
#   define QES_ZFUNGETC fungetc
#   define QES_ZERR ferror
#   define QES_ZEOF feof
#   define QES_ZBUFFER(fp, sz) setvbuf(fp, NULL, _IOFBF, sz)
#   define QES_ZSEEK fseek
#   define QES_ZTELL ftell
#   define QES_ZREWIND rewind
#endif

#endif /* QES_CONFIG_H */`

**Comment by dougwyu** [comment]
`/*
 * Copyright 2015 Kevin Murray <spam@kdmurray.id.au>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * ============================================================================
 *
 *       Filename:  qes_config.h.in
 *
 *    Description:  Define various things from CMake.
 *
 *        Created:  15/08/14 12:09:59
 *        License:  GPLv3+
 *       Compiler:  gcc, clang
 *
 *         Author:  Kevin Murray, spam@kdmurray.id.au
 *
 * ============================================================================
 */

#ifndef QES_CONFIG_H
#define QES_CONFIG_H

#define LIBQES_VERSION "0.3.3-2-ge23af27"
#define GETLINE_FOUND
#define STRNDUP_FOUND
#define ZLIB_FOUND
#define GZBUFFER_FOUND
/* #undef OPENMP_FOUND */
#define ASPRINTF_FOUND
#define VASPRINTF_FOUND

/* Definitions to make changing fp type easy */
#ifdef ZLIB_FOUND
#   include <zlib.h>
#   define QES_ZTYPE gzFile
#   define QES_ZOPEN gzopen
#   define QES_ZDOPEN gzdopen
#   define QES_ZCLOSE gzclose
#   define QES_ZREAD gzread
#   define QES_ZWRITE gzwrite
#   define QES_ZFLUSH(fp) gzflush(fp, Z_SYNC_FLUSH)
#   define QES_ZFPRINTF gzprintf
#   define QES_ZFPUTS gzputs
#   define QES_ZFPUTC gzputc
#   define QES_ZFGETS gzgets
#   define QES_ZFGETC gzgetc
#   define QES_ZFUNGETC gzungetc
#   define QES_ZERR gzerror
#   define QES_ZEOF gzeof
#ifdef GZBUFFER_FOUND
#   define QES_ZBUFFER gzbuffer
#endif
#   define QES_ZSEEK gzseek
#   define QES_ZTELL gztell
#   define QES_ZREWIND gzrewind
#else
#   define QES_ZTYPE FILE*
#   define QES_ZOPEN fopen
#   define QES_ZCLOSE fclose
#   define QES_ZDOPEN fdopen
#   define QES_ZCLOSE fclose
#   define QES_ZREAD(fp, buf, ln) fread(buf, 1, ln, fp)
#   define QES_ZWRITE(fp, buf, ln) fwrite(buf, 1, ln, fp)
#   define QES_ZFLUSH fflush
#   define QES_ZFPRINTF fprintf
#   define QES_ZFPUTS(fp, s) fputs(s, fp)
#   define QES_ZFPUTC(fp, c) fputc(c, fp)
#   define QES_ZFGETS(fp, s, l) fgets(s, l, fp)
#   define QES_ZFGETC fgetc
#   define QES_ZFUNGETC fungetc
#   define QES_ZERR ferror
#   define QES_ZEOF feof
#   define QES_ZBUFFER(fp, sz) setvbuf(fp, NULL, _IOFBF, sz)
#   define QES_ZSEEK fseek
#   define QES_ZTELL ftell
#   define QES_ZREWIND rewind
#endif

#endif /* QES_CONFIG_H */
`

**Comment by kdmurray91** [comment]
Just to confirm, you've been able to compile and run Axe on your system using the manual clang command? If so, I'm none the wiser as to why it didn't work using cmake, but at least it compiles!

**Comment by dougwyu** [comment]
yes, i ran axe successfully on the tutorial dataset after manually compiling with your commands.

doug
-- 
Prof. Douglas W. Yu
School of Biological Sciences, University of East Anglia, Norwich, Norfolk  NR4 7TJ  UK,  mob +44-7510-308-272
Kunming Institute of Zoology, 21 Qingsong Lu, Kunming, Yunnan 650201 China 中国云南昆明市盘龙区茨坝青松路21号, ofc +86-871-519 9178, mob 1860-871-7369
www.uea.ac.uk/bio/People/Academic/Douglas+Yu <http://www.uea.ac.uk/bio/People/Academic/Douglas+Yu>, eastanglia.academia.edu/DouglasYu/Papers <http://eastanglia.academia.edu/DouglasYu/Papers> for pdfs

**Comment by kdmurray91** [comment]
Great, sorry it was a bit arduous!
