### ISSUE TITLE
Finishes without error on a corrupt gzipped sequence file

### ISSUE THREAD

**Issue by relshire** [kdmurray91/axe#5]
While working with a corrupt gzipped sequence file, axe-demux 'finished' but did not throw an error or otherwise alert me to a problem. Having fraction of the expected sequences in the summary table did alert me to the problem. 

I'm not sure how one would catch this error....

In any case. This works very well. Thank Kevin for making it. This is the first program I've used that takes advantage of the hamming distances that I designed into the molecular part of GBS!

**Comment by kdmurray91** [comment]
Hi Rob,

Thanks for the bug report. That looks like a bug to me, though this could actually be quite low-level (within the C libraries I use for parsing). How is your gzip file corrupted? If you can generate a minimal failing example file, I'll debug this locally. Otherwise I can give you tips on how to debug this at your end.

Cheers,
K

**Comment by relshire** [comment]
Hi Kevin,
The files I am working with are around 12G each. The file got corrupted during copying. Not sure what the nature of the corruption is. I've tried to find instructions on how to corrupt a gz file, but only find fixes. :) Happy to take some tips on debugging.

Best,

Rob

**Comment by kdmurray91** [comment]
Hi Rob,

Sorry it's taken a while to get back to you.

Do you have the original files available?

Cheers,
K

**Comment by kdmurray91** [comment]
Hi Rob, I just made a gitter chat room for Axe. We can continue the discussion there if you prefer a more real-time discussion.

Cheers,
K

**Comment by relshire** [comment]
HI Kevin,Sorry for the slow reply. I've been at an Open Source // Open Society conference in Wellington. Some cool stuff going on here. Will get back home late in the afternoon tomorrow and will pick up this thread.Best,Rob----- Original Message -----
