### ISSUE TITLE
Barcode file must be provided

### ISSUE THREAD

**Issue by qgao2** [kdmurray91/axe#7]
Hello Kevin,
I got this error when I use axe-demux: Barcode file must be provided. 
The script is as below, and I am trying to demultiplex a fastq file with 96 samples. 
axe-demux -m -barcodes barcode_box5_axe.csv -f Lane_2_S2_L002_R1_001.fastq -F axe_demux

The barcode file (csv file, separated by Tab) looks like this:
Barcode	ID
ACGAGTGCGT	Lane2Sample1
ACGCTCGACA	Lane2Sample2
AGACGCACTC	Lane2Sample3
AGCACTGTAG	Lane2Sample4
ATCAGACACG	Lane2Sample5

**Comment by kdmurray91** [comment]
Hi! Thanks for your interest in Axe. I think one of the options you're using needs a small adjustment.

```
axe-demux -b barcode_box5_axe.csv -f Lane_2_S2_L002_R1_001.fastq -F axe_demux
```

If you want to use the -m option, it requires a number of mismatches to be specified (e.g. `-m 1` to allow up to 1 mismatch).

Let me know if that fixes the problem for you!
Cheers,
K

**Comment by qgao2** [comment]
Great, now it works!
Thank you, Kevin.
